;;;; attractor-aot.asd -- a de Jong attractor, drawn by Lisp, on a phone, with
;;;; its hot loop and its drawRect: IMP compiled ahead of time, in C.

(defsystem "attractor-aot"
  :defsystem-depends-on ("asdf-ios-app")
  :class :ios-app-system
  :build-operation "ios-app-op"
  :entry-point "attractor-aot:start"
  :description "Two million points of arithmetic, and a view whose drawRect: is Lisp."
  :version "1.0.0"
  :serial t
  ;; slynk is not on Quicklisp under that name: point your source registry at
  ;; sly's slynk/ directory. Drop this and :REMOTE-REPL below if you would
  ;; rather build the demo without one -- everything but the live redefinition
  ;; works the same.
  :depends-on ("slynk")
  :components ((:file "glue-package")
               (:file "attractor-aot"))

  :bundle-identifier "org.asdf-ios-app.attractor-aot"
  :bundle-name "AttractorAOT"
  :bundle-executable "attractor-aot"

  ;; A device build must be signed, and is built for only when it can be:
  ;; identity, team and profile come from the environment at read time --
  ;; IOS_SIGNING_IDENTITY, IOS_DEVELOPMENT_TEAM, IOS_PROVISIONING_PROFILE --
  ;; so that nobody's identity is committed here.  Unset, this is a simulator
  ;; build, ad hoc signed, as usual.
  :bundle-platforms #.(if (uiop:getenv "IOS_SIGNING_IDENTITY")
                          '(:simulator :device)
                          '(:simulator))
  :code-signing-identity #.(or (uiop:getenv "IOS_SIGNING_IDENTITY") :automatic)
  :development-team #.(uiop:getenv "IOS_DEVELOPMENT_TEAM")
  :provisioning-profile #.(uiop:getenv "IOS_PROVISIONING_PROFILE")
  :bundle-orientations (:portrait :landscape-left :landscape-right)

  ;; The icon is the attractor, iterated four million times at 1024x1024 --
  ;; generated by make-icon.py rather than drawn. actool compiles the
  ;; catalogue and reports which Info.plist keys the result needs.
  :bundle-icon "Attractor.xcassets"

  ;; The C side. Cross-compiled only, which is what lets it use FFI:C-INLINE.
  ;; Written when a drawRect: IMP receiving a CGRect by value was out of reach
  ;; of ECL's dynamic FFI; it is not any more, and the other examples define
  ;; such methods in Lisp through objc -- attractor-dynamic is this same figure
  ;; that way. This one keeps its C, because a
  ;; drawRect: body that calls CoreGraphics two million times a frame is a
  ;; reasonable thing to have in C.
  :bundle-trampolines ("glue.lisp")
  :bundle-frameworks ("UIKit" "Foundation" "CoreGraphics")

  ;; The last part of the demonstration: connect and redefine STEP-POINT while
  ;; the phone is drawing. Wrap anything that touches the view in
  ;; IOS-APP-RUNTIME:WITH-MAIN-THREAD -- slynk evaluates on a worker. On a
  ;; device, iproxy 4005:4005 first; examples/live/ is the walkthrough.
  :remote-repl t)
