;;;; attractor.asd -- a de Jong attractor, drawn by Lisp, on a phone.

(defsystem "attractor"
  :defsystem-depends-on ("asdf-ios-app")
  :class :ios-app-system
  :build-operation "ios-app-op"
  :entry-point "attractor:start"
  :description "Two million points of arithmetic, and a view whose drawRect: is Lisp."
  :version "1.0.0"
  :serial t
  ;; slynk is not on Quicklisp under that name: point your source registry at
  ;; sly's slynk/ directory. Drop this and :REMOTE-REPL below if you would
  ;; rather build the demo without one -- everything but the live redefinition
  ;; works the same.
  :depends-on ("slynk")
  :components ((:file "glue-package")
               (:file "attractor"))

  :bundle-identifier "org.asdf-ios-app.attractor"
  :bundle-name "Attractor"
  :bundle-executable "attractor"
  :bundle-platforms (:simulator)
  :bundle-orientations (:portrait :landscape-left :landscape-right)

  ;; The icon is the attractor, iterated four million times at 1024x1024 --
  ;; generated by make-icon.py rather than drawn. actool compiles the
  ;; catalogue and reports which Info.plist keys the result needs.
  :bundle-icon "Attractor.xcassets"

  ;; The C side. Cross-compiled only, which is what lets it use FFI:C-INLINE:
  ;; a drawRect: IMP receives a CGRect BY VALUE, and no Lisp-side FFI on ECL
  ;; can name an aggregate.
  :bundle-trampolines ("glue.lisp")
  :bundle-frameworks ("UIKit" "Foundation" "CoreGraphics")

  ;; The last part of the demonstration: connect and redefine STEP-POINT while
  ;; the phone is drawing. Wrap anything that touches the view in
  ;; IOS-APP-RUNTIME:WITH-MAIN-THREAD -- slynk evaluates on a worker.
  :remote-repl t)
