;;;; link.lisp -- compile the Objective-C shim and link the executable.
;;;;
;;;; The only generated C in the project is one header. Everything else in
;;;; src/objc/ is a real file a person can read, edit and syntax-check; what
;;;; varies per build is confined to #defines.

(in-package #:asdf-ios-app)

(defparameter +bootstrap-sources+
  '("ECLBoot.m" "ECLAppDelegate.m" "ECLMain.m" "LispTarget.m")
  "The Objective-C we ship and compile into every app, in order. A test asserts
this agrees with src/objc/ in both directions, because the two drift apart
otherwise -- the same reason +REQUIRED-TOOLS+ has one.")

(defun objc-directory ()
  (system-file "src/objc/"))

(defun build-header-path (cache)
  (uiop:subpathname cache "ios-app-build.h"))

(defun modules-header-path (cache)
  (uiop:subpathname cache "ios-app-modules.h"))

(defun write-build-header (cache &key name delegate boot-form modules)
  "The generated C, which is two files rather than one.

ios-app-build.h holds only strings, so UIKit-side files can include it.
ios-app-modules.h declares init entry points, whose argument type is cl_object,
so it can only be included where <ecl/ecl.h> already has been -- which is
ECLBoot.m and nowhere else. That is the same translation-unit split the shim
itself observes: ECL's headers define bare `t' and other very short names, and
nothing that touches UIKit may see them."
  (when (find #\Newline boot-form)
    ;; A C string literal cannot span lines, and the pretty printer will break
    ;; a long form without being asked. Caught here because the compiler error
    ;; it causes points at the generated header rather than at the cause.
    (barf "The boot form contains a newline, which cannot be a C string:~%~a"
          boot-form))
  (let ((build (build-header-path cache))
        (modules-header (modules-header-path cache)))
    (write-file-if-changed
     build
     (with-output-to-string (out)
      (format out "/* ios-app-build.h -- generated by asdf-ios-app. ~
Do not edit.~%   Strings only: this is included from UIKit-side files too. */~%~
#ifndef IOS_APP_BUILD_H~%#define IOS_APP_BUILD_H~%~%")
      (format out "#define IOS_APP_NAME     ~s~%" name)
      (format out "#define IOS_APP_DELEGATE ~s~%~%" (or delegate "ECLAppDelegate"))
      (format out "#define IOS_APP_BOOT_FORM \\~%  ~s~%~%" boot-form)
      (format out "#endif~%")))

    (write-file-if-changed
     modules-header
     (with-output-to-string (out)
      (format out "/* ios-app-modules.h -- generated by asdf-ios-app. ~
Do not edit.~%   Include only after <ecl/ecl.h>: these take a cl_object. */~%~
#ifndef IOS_APP_MODULES_H~%#define IOS_APP_MODULES_H~%~%")
      (dolist (module modules)
        (format out "extern void ~a(cl_object);~%" (cdr module)))
      (format out "~%/* Names are declared present BEFORE the inits run: a module's own~%~
   load-time code may REQUIRE another, and REQUIRE otherwise hunts for a .fas~%~
   under the ECLDIR compiled into this build -- which in the simulator is a~%~
   real, readable directory on the Mac. */~%")
      (format out "#define IOS_APP_MODULES(X) \\~%")
      (if modules
          (loop for (module-name . init) in modules
                for remaining on modules
                do (format out "  X(~s, ~a)~:[~; \\~]~%"
                           module-name init (rest remaining)))
          (format out "  /* none */~%"))
      (format out "~%#endif~%")))
    (values build modules-header)))

;;; ------------------------------------------------------------------
;;; Objective-C

(defun platform-clang-flags (platform)
  (let* ((p (if (ios-platform-p platform) platform (find-platform platform)))
         (flags (prefix-build-flags (platform-prefix p))))
    (list "-arch" (getf flags :arch)
          (or (getf flags :min-flag)
              (format nil "~a=15.0" (platform-min-flag p)))
          "-isysroot" (getf flags :sdk))))

(defun objc-object-is-current-p (source object cache)
  "Whether an Objective-C object can be reused.

The generated headers count as inputs: everything here includes at least one of
them, and their contents change when the app's name, delegate or module list
does. WRITE-FILE-IF-CHANGED is what keeps their write dates meaningful."
  (and (not *force-compile*)
       (probe-file object)
       (let ((newest (reduce #'max
                             (mapcar #'file-write-date
                                     (remove nil
                                             (list source
                                                   (probe-file (build-header-path cache))
                                                   (probe-file (modules-header-path cache))))))))
         (>= (file-write-date object) newest))))

(defun compile-objc-file (source platform cache &key extra-flags)
  (let* ((p (if (ios-platform-p platform) platform (find-platform platform)))
         (output (make-pathname :name (pathname-name source) :type "o"
                                :defaults cache)))
    (when (objc-object-is-current-p source output cache)
      (return-from compile-objc-file output))
    (ensure-directories-exist output)
    (run (append (list "/usr/bin/clang" "-x" "objective-c" "-c" "-fobjc-arc" "-O2")
                 (platform-clang-flags p)
                 (list "-I" (uiop:native-namestring
                             (prefix-include (platform-prefix p)))
                       "-I" (uiop:native-namestring cache)
                       "-I" (uiop:native-namestring (objc-directory)))
                 extra-flags
                 (list "-o" (uiop:native-namestring output)
                       (uiop:native-namestring source)))
         :echo-error t)
    output))

(defun compile-objc-sources (platform cache &key user-sources own-main extra-flags)
  "Compile the shipped shim plus any sources the application supplies.

OWN-MAIN suppresses ECLMain.m, so an application that needs its own main() is
not fighting ours."
  (let ((shipped (remove-if (lambda (name)
                              (and own-main (string= name "ECLMain.m")))
                            +bootstrap-sources+)))
    (append (mapcar (lambda (name)
                      (compile-objc-file (uiop:subpathname (objc-directory) name)
                                         platform cache :extra-flags extra-flags))
                    shipped)
            (mapcar (lambda (source)
                      (compile-objc-file source platform cache
                                         :extra-flags extra-flags))
                    user-sources))))

;;; ------------------------------------------------------------------
;;; linking

(defun module-library-flags (spec)
  "-l flags for the ECL modules this app asked for, plus the directory they
live in. They must precede -lecl: they depend on it."
  (let* ((platform (spec-platform spec))
         (modules (prefix-module-directory (platform-prefix platform))))
    (append (list (format nil "-L~a" (uiop:native-namestring modules)))
            (mapcar (lambda (m) (format nil "-l~a" m)) (spec-ecl-modules spec)))))

(defun link-executable (spec library objects)
  "Link the flat executable. Order is load-bearing: our objects, then the
application's library, then ECL's modules, then ECL itself."
  (let* ((platform (spec-platform spec))
         (prefix (platform-prefix platform))
         (output (executable-path spec)))
    (ensure-directories-exist output)
    (run (append (list "/usr/bin/clang")
                 (platform-clang-flags platform)
                 (list "-o" (uiop:native-namestring output))
                 (mapcar #'uiop:native-namestring objects)
                 (list (uiop:native-namestring library))
                 (module-library-flags spec)
                 (list (format nil "-L~a" (uiop:native-namestring
                                           (prefix-lib prefix)))
                       "-lecl" "-leclgc" "-leclgmp" "-leclffi")
                 (loop for framework in (spec-frameworks spec)
                       collect "-framework" collect framework)
                 (mapcar #'uiop:native-namestring (spec-static-libraries spec))
                 (spec-link-flags spec))
         :echo-error t)
    output))

(defun mach-o-platform (path)
  (let ((out (run (list "/usr/bin/otool" "-lv" (uiop:native-namestring path))
                  :ignore-error-status t)))
    (cond ((search "IOSSIMULATOR" out) "IOSSIMULATOR")
          ((search "LC_VERSION_MIN_IPHONEOS" out) "IOS")
          ((search "platform IOS" out) "IOS")
          (t "unknown"))))

(defun verify-mach-o-platform (spec)
  "Assert the linked binary is for the platform we think it is.

A stale object from the other platform can link cleanly, and the failure it
produces later -- an app that installs and will not launch -- says nothing
about why."
  (let* ((expected (platform-mach-o-platform (spec-platform spec)))
         (actual (mach-o-platform (executable-path spec))))
    (unless (string= expected actual)
      (barf "~a is a ~a binary but this is a ~a build. A stale object from the ~
             other platform is the usual cause; the object cache is per ~
             platform, so check for one built by hand."
            (uiop:native-namestring (executable-path spec)) actual expected))
    actual))
