;;;; link.lisp -- compile the Objective-C shim and link the executable.
;;;;
;;;; The only generated C in the project is one header. Everything else in
;;;; src/objc/ is a real file a person can read, edit and syntax-check; what
;;;; varies per build is confined to #defines.

(in-package #:asdf-ios-app)

(defparameter +bootstrap-sources+
  '("ECLBoot.m" "ECLAppDelegate.m" "ECLMain.m" "LispTarget.m")
  "The Objective-C we ship and compile into every app, in order. A test asserts
this agrees with src/objc/ in both directions, because the two drift apart
otherwise -- the same reason +REQUIRED-TOOLS+ has one.")

(defun objc-directory ()
  (system-file "src/objc/"))

(defun build-header-path (cache)
  (uiop:subpathname cache "ios-app-build.h"))

(defun modules-header-path (cache)
  (uiop:subpathname cache "ios-app-modules.h"))

(defun write-build-header (cache &key name delegate boot-form modules)
  "The generated C, which is two files rather than one.

ios-app-build.h holds only strings, so UIKit-side files can include it.
ios-app-modules.h declares init entry points, whose argument type is cl_object,
so it can only be included where <ecl/ecl.h> already has been -- which is
ECLBoot.m and nowhere else. That is the same translation-unit split the shim
itself observes: ECL's headers define bare `t' and other very short names, and
nothing that touches UIKit may see them."
  (when (find #\Newline boot-form)
    ;; A C string literal cannot span lines, and the pretty printer will break
    ;; a long form without being asked. Caught here because the compiler error
    ;; it causes points at the generated header rather than at the cause.
    (barf "The boot form contains a newline, which cannot be a C string:~%~a"
          boot-form))
  (let ((build (build-header-path cache))
        (modules-header (modules-header-path cache)))
    (write-file-if-changed
     build
     (with-output-to-string (out)
      (format out "/* ios-app-build.h -- generated by asdf-ios-app. ~
Do not edit.~%   Strings only: this is included from UIKit-side files too. */~%~
#ifndef IOS_APP_BUILD_H~%#define IOS_APP_BUILD_H~%~%")
      (format out "#define IOS_APP_NAME     ~s~%" name)
      (format out "#define IOS_APP_DELEGATE ~s~%~%" (or delegate "ECLAppDelegate"))
      (format out "#define IOS_APP_BOOT_FORM \\~%  ~s~%~%" boot-form)
      (format out "#endif~%")))

    (write-file-if-changed
     modules-header
     (with-output-to-string (out)
      (format out "/* ios-app-modules.h -- generated by asdf-ios-app. ~
Do not edit.~%   Include only after <ecl/ecl.h>: these take a cl_object. */~%~
#ifndef IOS_APP_MODULES_H~%#define IOS_APP_MODULES_H~%~%")
      (dolist (module modules)
        (format out "extern void ~a(cl_object);~%" (cdr module)))
      (format out "~%/* Names are declared present BEFORE the inits run: a module's own~%~
   load-time code may REQUIRE another, and REQUIRE otherwise hunts for a .fas~%~
   under the ECLDIR compiled into this build -- which in the simulator is a~%~
   real, readable directory on the Mac. */~%")
      (format out "#define IOS_APP_MODULES(X) \\~%")
      (if modules
          (loop for (module-name . init) in modules
                for remaining on modules
                do (format out "  X(~s, ~a)~:[~; \\~]~%"
                           module-name init (rest remaining)))
          (format out "  /* none */~%"))
      (format out "~%#endif~%")))
    (values build modules-header)))

;;; ------------------------------------------------------------------
;;; Objective-C

(defun platform-clang-flags (platform)
  (let* ((p (if (ios-platform-p platform) platform (find-platform platform)))
         (flags (prefix-build-flags (platform-prefix p))))
    (list "-arch" (getf flags :arch)
          (or (getf flags :min-flag)
              (format nil "~a=15.0" (platform-min-flag p)))
          "-isysroot" (getf flags :sdk))))

(defun objc-object-is-current-p (source object cache)
  "Whether an Objective-C object can be reused.

The generated headers count as inputs: everything here includes at least one of
them, and their contents change when the app's name, delegate or module list
does. WRITE-FILE-IF-CHANGED is what keeps their write dates meaningful."
  (and (not *force-compile*)
       (probe-file object)
       (let ((newest (reduce #'max
                             (mapcar #'file-write-date
                                     (remove nil
                                             (list source
                                                   (probe-file (build-header-path cache))
                                                   (probe-file (modules-header-path cache))))))))
         (>= (file-write-date object) newest))))

(defun compile-objc-file (source platform cache &key extra-flags)
  (let* ((p (if (ios-platform-p platform) platform (find-platform platform)))
         (output (make-pathname :name (pathname-name source) :type "o"
                                :defaults cache)))
    (when (objc-object-is-current-p source output cache)
      (return-from compile-objc-file output))
    (ensure-directories-exist output)
    (run (append (list "/usr/bin/clang" "-x" "objective-c" "-c" "-fobjc-arc" "-O2")
                 (platform-clang-flags p)
                 (list "-I" (uiop:native-namestring
                             (prefix-include (platform-prefix p)))
                       "-I" (uiop:native-namestring cache)
                       "-I" (uiop:native-namestring (objc-directory)))
                 extra-flags
                 (list "-o" (uiop:native-namestring output)
                       (uiop:native-namestring source)))
         :echo-error t)
    output))

(defun compile-objc-sources (platform cache &key user-sources own-main extra-flags)
  "Compile the shipped shim plus any sources the application supplies.

OWN-MAIN suppresses ECLMain.m, so an application that needs its own main() is
not fighting ours."
  (let ((shipped (remove-if (lambda (name)
                              (and own-main (string= name "ECLMain.m")))
                            +bootstrap-sources+)))
    (append (mapcar (lambda (name)
                      (compile-objc-file (uiop:subpathname (objc-directory) name)
                                         platform cache :extra-flags extra-flags))
                    shipped)
            (mapcar (lambda (source)
                      (compile-objc-file source platform cache
                                         :extra-flags extra-flags))
                    user-sources))))

;;; ------------------------------------------------------------------
;;; linking

(defun module-library-flags (spec)
  "-l flags for the ECL modules this app asked for, plus the directory they
live in. They must precede -lecl: they depend on it."
  (let* ((platform (spec-platform spec))
         (modules (prefix-module-directory (platform-prefix platform))))
    (append (list (format nil "-L~a" (uiop:native-namestring modules)))
            (mapcar (lambda (m) (format nil "-l~a" m)) (spec-ecl-modules spec)))))

(defun link-executable (spec library objects)
  "Link the flat executable. Order is load-bearing: our objects, then the
application's library, then ECL's modules, then ECL itself."
  (let* ((platform (spec-platform spec))
         (prefix (platform-prefix platform))
         (output (executable-path spec)))
    (ensure-directories-exist output)
    (run (append (list "/usr/bin/clang")
                 (platform-clang-flags platform)
                 (list "-o" (uiop:native-namestring output))
                 (mapcar #'uiop:native-namestring objects)
                 (list (uiop:native-namestring library))
                 (module-library-flags spec)
                 (list (format nil "-L~a" (uiop:native-namestring
                                           (prefix-lib prefix)))
                       "-lecl" "-leclgc" "-leclgmp" "-leclffi")
                 (loop for framework in (spec-frameworks spec)
                       collect "-framework" collect framework)
                 ;; Force-loaded, every member: a static library named here
                 ;; is for Lisp to call BY NAME at run time, and the linker
                 ;; keeps an archive member only for a reference it can see
                 ;; at link time -- so a plain path links nothing, and the
                 ;; first dlsym finds nothing, with no error until then.
                 (loop for library in (spec-static-libraries spec)
                       collect (format nil "-Wl,-force_load,~a"
                                       (uiop:native-namestring library)))
                 (embedded-framework-link-flags spec)
                 (simulated-entitlements-link-flags spec)
                 (spec-link-flags spec))
         :echo-error t)
    output))

;;; ------------------------------------------------------------------
;;; simulated entitlements
;;;
;;; A simulator app is signed with no entitlements (sign.lisp says why), yet
;;; the simulator's securityd still wants to know the app's identifier and
;;; keychain access group before SecItemAdd will store anything: without
;;; them every Keychain call fails with errSecMissingEntitlement, -34018.
;;; Xcode squares this by LINKING the entitlements into the binary, as a
;;; __TEXT,__entitlements section (its *-Simulated.xcent file), where the
;;; simulator reads them and SpringBoard, which only checks the signature,
;;; never sees them.  Measured: with the section and an ad-hoc signature
;;; the app launches and the Keychain works; with the same plist in the
;;; signature instead, SpringBoard refuses the launch.
;;;
;;; The prefix on the identifier is the team when one is given and a
;;; placeholder otherwise; the simulator does not check it, only that the
;;; access group and the identifier agree.

(defun simulated-entitlements-form (spec)
  (let ((app-id (format nil "~a.~a" (or (spec-team-id spec) "SIMULATOR")
                        (spec-identifier spec))))
    `(:dict ("application-identifier" . ,app-id)
            ("keychain-access-groups" . (:array ,app-id)))))

(defun simulated-entitlements-link-flags (spec)
  "The -sectcreate that embeds a simulator build's entitlements, or nothing.

:IOS-DEFAULT derives them from the identifier; a file is embedded as it is;
NIL embeds nothing.  Device builds get theirs from the signature and none of
this."
  (let ((e (spec-entitlements spec)))
    (when (and (platform-simulator-p (spec-platform spec)) e)
      (let ((path (etypecase e
                    (pathname e)
                    (string (pathname e))
                    (symbol
                     (assert (eq e :ios-default))
                     (let ((path (sibling-file (spec-root spec)
                                               "simulated-entitlements.plist")))
                       (lint-plist (write-plist (simulated-entitlements-form spec) path))
                       path)))))
        (list (format nil "-Wl,-sectcreate,__TEXT,__entitlements,~a"
                      (uiop:native-namestring path)))))))

;;; ------------------------------------------------------------------
;;; embedded frameworks
;;;
;;; A framework built for the platform, shipped in Frameworks/ at the bundle
;;; root and linked against.  Swift, most likely: a framework with no
;;; Objective-C surface -- CryptoKit, Swift Charts, SwiftUI, FoundationModels
;;; -- is reached from Lisp through a hundred lines of @objc Swift, and that
;;; Swift has to ship as a framework of its own.  iOS has carried the Swift
;;; runtime since 12.2, so nothing else needs to travel with it.
;;;
;;; The one thing to get right is the install name.  dyld finds the framework
;;; through the rpath the executable is linked with, and only if the
;;; framework calls itself @rpath/<Name>.framework/<Name>; a framework built
;;; without -install_name names its build directory instead, which exists on
;;; the Mac and not on the phone, and the app dies at launch with dyld's
;;; "Library not loaded".  So the install name is checked before the build
;;; goes any further, and the message says what to pass.

(defun install-name (binary)
  "The install name a dynamic library carries, from otool -D."
  (let ((lines (remove "" (uiop:split-string
                           (run (list "/usr/bin/otool" "-D" (uiop:native-namestring binary)))
                           :separator '(#\Newline))
                       :test #'string=)))
    ;; The first line is the file name followed by a colon; the second is
    ;; the install name.
    (string-trim " " (or (second lines) ""))))

(defun check-embedded-framework (spec framework)
  (let ((platform (spec-platform spec)))
    (unless (uiop:directory-exists-p framework)
      (barf "No framework at ~a. A framework is built per platform, and this ~
             is a ~a build: is that one built?"
            (uiop:native-namestring framework) (platform-name platform)))
    (let ((binary (framework-binary framework)))
      (unless (probe-file binary)
        (barf "~a has no ~a inside it. An iOS framework keeps its Mach-O at its ~
               root, under the framework's own name."
              (uiop:native-namestring framework) (framework-name framework)))
      (let ((expected (platform-mach-o-platform platform))
            (actual (mach-o-platform binary)))
        (unless (string= expected actual)
          (barf "~a is a ~a binary but this is a ~a build."
                (uiop:native-namestring binary) actual expected)))
      (let ((wanted (format nil "@rpath/~a.framework/~a"
                            (framework-name framework) (framework-name framework)))
            (actual (install-name binary)))
        (unless (string= wanted actual)
          (barf "~a has the install name ~s, and dyld will look there on the ~
                 device. Build it with -Xlinker -install_name -Xlinker ~a ~
                 (swiftc) or -install_name ~a (clang)."
                (uiop:native-namestring binary) actual wanted wanted))))
    framework))

(defun install-embedded-frameworks (spec)
  "Copy :BUNDLE-EMBEDDED-FRAMEWORKS into Frameworks/, after checking each."
  (let ((frameworks (spec-embedded-frameworks spec)))
    (when frameworks
      (let ((directory (frameworks-directory spec)))
        (ensure-directories-exist directory)
        (dolist (framework frameworks)
          (check-embedded-framework spec framework)
          (run (list "/bin/cp" "-R"
                     (string-right-trim "/" (uiop:native-namestring framework))
                     (uiop:native-namestring directory))))))
    frameworks))

(defun embedded-framework-link-flags (spec)
  "-F for where each framework was built and -framework for its name, then
one rpath so dyld looks in the bundle's Frameworks/ at run time."
  (let ((frameworks (spec-embedded-frameworks spec)))
    (when frameworks
      (append (loop for framework in frameworks
                    collect (format nil "-F~a"
                                    (uiop:native-namestring
                                     (uiop:pathname-parent-directory-pathname
                                      (uiop:ensure-directory-pathname framework))))
                    collect "-framework"
                    collect (framework-name framework))
              (list "-Xlinker" "-rpath" "-Xlinker" "@executable_path/Frameworks")))))

(defun mach-o-platform (path)
  (let ((out (run (list "/usr/bin/otool" "-lv" (uiop:native-namestring path))
                  :ignore-error-status t)))
    (cond ((search "IOSSIMULATOR" out) "IOSSIMULATOR")
          ((search "LC_VERSION_MIN_IPHONEOS" out) "IOS")
          ((search "platform IOS" out) "IOS")
          (t "unknown"))))

(defun verify-mach-o-platform (spec)
  "Assert the linked binary is for the platform we think it is.

A stale object from the other platform can link cleanly, and the failure it
produces later -- an app that installs and will not launch -- says nothing
about why."
  (let* ((expected (platform-mach-o-platform (spec-platform spec)))
         (actual (mach-o-platform (executable-path spec))))
    (unless (string= expected actual)
      (barf "~a is a ~a binary but this is a ~a build. A stale object from the ~
             other platform is the usual cause; the object cache is per ~
             platform, so check for one built by hand."
            (uiop:native-namestring (executable-path spec)) actual expected))
    actual))
